### ISSUE TITLE
Epic: Support OCP with submariner on VMWare

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#116]
**What would you like to be added**:
Proposal is to fully support connecting multiple OCP clusters on VMWare using Submariner.

**Why is this needed**:
Aim of this proposal is to list and track steps needed to fill any gaps and allow full support for such deployments.

**UPDATE**
Investigations have confirmed that there is nothing that needs to be done to prepare cloud for VM Ware, in subctl or OCM. Expectation is that VMWare should work without any changes, except when using NSX which is for now outside scope of this EPIC.

**Work Items**

Based on results of investigations, only effort required is testing.
- [ ] Add VMWare to Submariner Testday
- [ ] Run QE on VMWare

**Comment by dfarrell07** [comment]
Should we move this epic to the enhancements repo?

**Comment by nyechiel** [comment]
An interesting data point: feedback from users suggests that Submariner just works on vSphere without special preparation, at least on non-NSX environments. From @sridhargaddam: "If customers use NSX, then i would guess that outbound traffic might be allowed by default (which is usually the case even with other public clouds), but the ingress traffic (meeting Submariner pre-requisites) needs to be explicitly allowed. So, as part of cloud-prepare for VmWare, I would imagine that it should first check if NSX is deployed and if so, configure the required firewall ports."

**Comment by maayanf24** [comment]
Nothing to do here at this point
