### ISSUE TITLE
Write an enhancement proposal for OVN InterConnect support

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#142]
**What would you like to be added**:

Add support in Submariner to support OVN interconnect

**Why is this needed**:

The OVN is moving to a new architecture using an OVN interconnect. This would have an impact on Submariner. We need to test Submariner with the new implementation and make the necessary changes.

Enhancement PR: https://github.com/submariner-io/enhancements/pull/163

**Comment by maayanf24** [comment]
@aswinsuryan - Can you add sizing information and an enhancement proposal for this?

**Comment by aswinsuryan** [comment]
@maayanf24 Yes I will work on it.

**Comment by aswinsuryan** [comment]
Was able to deploy OVN with IC enabled using [this](https://github.com/numansiddique/ovn-kubernetes/tree/multiple_zone_support) branch. Followed the instructions in the readme and some of the scripts were modified to rectify issues that we face when multiple clusters deployed. @sridhargaddam  documented  the changes to be made [here](https://gist.github.com/sridhargaddam/f5428147924a2673e58697b892ea6194)

A cluster with a single zone was tried by running the above steps with these flags

```
export KIND_NUM_ADDITIONAL_ZONES=0
export KIND_NUM_WORKER=2
export OVN_INTERCONNECT_ENABLE=true
```

The submariner e2e failed since the  OVN transit switch that connects two different zone uses the [same CIDR]( https://github.com/numansiddique/ovn-kubernetes/blob/zone_support/go-controller/pkg/clustermanager/clustermanager.go#L41) as the Submariner Router.

After changing the IP in OVN to a different CIDR, `244.254.0.0/16`(changed in OVN as it was easier to test), Submariner tests passed

So the Submariner router needs to use a different CIDR.

Now need to verify submariner tests with multiple zones.
