### ISSUE TITLE
Submariner on single node clusters

### ISSUE THREAD

**Issue by yboaron** [submariner-io/enhancements#145]
**What would you like to be added**:
Add Submariner support for single node cluster.
**Why is this needed**:

The cloud native approach to developing and deploying applications is increasingly being adopted in the context of edge computing.  

Some infrastructure providers and application owners want a consistent workload life cycle approach across the business, this includes also their edge architectures. sites that might have intermittent or very low bandwidth connectivity back to a central site. in edge/remote locations, as the distance between an edge site and the central management hub grows, the physical space for systems decreases. This means these edge locations operate with very limited space as well as power and cooling, creating an environment suited for a single server. 

Single node K8S/Openshift cluster offers both control and worker node capabilities in a single server.

**Tasks**:
- Check Submariner on SNO using LB 
-

**Comment by yboaron** [comment]
I managed to successfully deploy Submariner on OCP single node cluster on AWS and GCP.
Check below table for more details.



<b style="font-weight:normal;" id="docs-internal-guid-15d5839a-7fff-b459-7e6e-9f09381076fe"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Submariner version: 0.14&nbsp; using Subctl</span></p><br /><div dir="ltr" style="margin-left:-64.5pt;" align="left">

Cluster-A | Cluster-B | Submariner configuration | Subctl verify results
-- | -- | -- | --
AWS multi nodes (OCP 4.11) | AWS SNOopenshiftSDN (OCP 4.11) | Globalnet, Cluster-B prepare:Manual GW node labeling, Subctl join –load-balancer | Ran 18 of 44 Specs in 603.462 secondsSUCCESS! -- 18 Passed \| 0 Failed \| 0 Pending \| 26 Skipped
AWS multi nodes(OCP 4.11) | AWS SNOOVNKubernetes (OCP 4.11) | Globalnet, Cluster-B prepare:Manual GW node labeling, Subctl join –load-balancer | Ran 18 of 44 Specs in 603.462 secondsSUCCESS! -- 18 Passed \| 0 Failed \| 0 Pending \| 26 Skipped
AWS multi nodes(OCP 4.11) | GCP SNOOVNKubernetes(OCP 4.11) | Globalnet, Cluster-B prepare:Manual GW node labeling, Subctl join –load-balancer | Ran 20 of 44 Specs in 691.076 secondsSUCCESS! -- 20 Passed \| 0 Failed \| 0 Pending \| 24 Skipped

</div><br /></b>

**Comment by nyechiel** [comment]
@yboaron is there a reason to keep this one open? are there any known gaps we need to track?

**Comment by yboaron** [comment]
@nyechiel I think we have completed the first phase, which is gap analysis for Submariner deployment on SNO clusters.

For the broader context, we still need to think about the implications (eg: topology size, bandwidth, etc.) of running Submariner on SNO clusters.

I assume that this issue can be closed at this point, we can reopen it when the topic is relevant again and discuss the open issues.
