### ISSUE TITLE
Remove the network plugin syncer from submariner

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#190]
* Remove the network-plugin-syncer

**Comment by nyechiel** [comment]
We also need to make sure we stop referencing it in `subctl`, e.g in places like `diagnose` and `related-images`.

**Comment by tpantelis** [comment]
> We also need to make sure we stop referencing it in `subctl`, e.g in places like `diagnose` and `related-images`.

I already have a local commit for that.
