### ISSUE TITLE
Analyze and update  subctl diagnose as per the new implementation

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#192]
Analyze and update subctl diagnose as per the new implementation as per the new changes.

**Comment by vthapar** [comment]
https://github.com/submariner-io/subctl/pull/883 Should have addressed all changes, mainly removal of networkplugin syncer bits. There is no other code in diagnose impacted by these changes.

https://github.com/submariner-io/subctl/pull/888 should take care of `subctl gather` changes.

**Comment by vthapar** [comment]
As of now nothing else needs to be done for this, so closing as complete.
