### ISSUE TITLE
Baremetal Support in Submariner

### ISSUE THREAD

**Issue by aswinsuryan** [submariner-io/enhancements#215]
## Epic Description
Baremetal Support in Submariner

## Acceptance Criteria

Submariner should be able to enable connectivity between baremetal clusters and cluster running in public cloud

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

**Comment by maayanf24** [comment]
All dev work is done
