### ISSUE TITLE
Submariner Repos OWNER Request

### ISSUE THREAD

**Issue by vthapar** [submariner-io/enhancements#217]
---
name: Submariner Owner Request
about: Request Owner rights on all Submariner repos
title: 'REQUEST: New Owner rights for vthapar'
labels: committer-request
assignees: ''

---

### GitHub Username
@vthapar 

### Code you are requesting Owner rights for
shipyard/\*
cloud-prepare/\*
admiral/\*
submariner/\*
lighthouse/\*
submariner-operator/\*
subctl/\*
submariner-website/\*
releases/\*
submariner-charts/\*

### Requirements
- [x] I have reviewed the contributor roles guidelines (https://submariner.io/community/contributor-roles/)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the submariner-dev e-mail list (https://groups.google.com/forum/#!forum/submariner-dev)
- [x] I have been actively contributing to Submariner for at least 3 months
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @skitt 
- @tpantelis 

### List of required reviews to Submariner project PRs
- At least 20 PRs to the relevant codebase that you reviewed, and at least 5 for which you were the primary reviewer
  - `https://github.com/submariner-io/lighthouse/pulls?q=is%3Apr+reviewed-by%3Avthapar+-author%3Avthapar`
  - `https://github.com/submariner-io/submariner-operator/pulls?q=is%3Apr+reviewed-by%3Avthapar+-author%3Avthapar`

**Comment by tpantelis** [comment]
+1

**Comment by tpantelis** [comment]
What's the next step?

**Comment by skitt** [comment]
+1
