### ISSUE TITLE
Add support for boringtun or wireguard-go in wireguard when kernel module is not available

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/enhancements#36]
https://github.com/cloudflare/boringtun It's a rust based, very performant implementation of wireguard.

https://github.com/WireGuard/wireguard-go is a go-based inplementation (performance to be checked)

**Comment by dfarrell07** [comment]
We don't seem to have a user or use-case driving this, and although it seems technically interesting, maybe we should close it until we do.
