### ISSUE TITLE
consider a tailscale cable driver (wireguard under the hood)

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/enhancements#37]
Using a subnet router would theoretically make it possible:

https://tailscale.com/kb/1019/subnets/

It's a managed wireguard on steroids, which would allow connecting also to existing legacy workloads
with ease.

It supports HTTP relay via their cloud servers for cases where NAT traversal is impossible, as well as
NAT hole punching techniques, etc...

**Comment by dfarrell07** [comment]
@tpantelis points out that there isn't a user/use-case driving this, maybe we should table it until there is one.

@donaldh points out there might be license issues if we use this for commercial purposes.
