### ISSUE TITLE
Consider implementing NAT-hole-punching techniques for all cable drivers in general

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/enhancements#38]
This would avoid the necessity of port mapping in a great deal of cases:

   https://en.wikipedia.org/wiki/UDP_hole_punching

Once the UDP hole is punched (if the router would allow that, of course),
then we can advertise that port as the port to be used for NATT discovery or UDP traffic.

**Comment by dfarrell07** [comment]
@sridhargaddam this sounds technically interesting but we don't have a user or use-case for it currently. Closing for now, we can re-open if someone has a reason to work on this.
