### ISSUE TITLE
E2E checks should abort on the first failure

### ISSUE THREAD

**Issue by skitt** [submariner-io/enhancements#45]
Currently, E2E tests run the full test suite, even when tests are failing. The failures often show up as time-outs, and a failing test suite thus takes a very long time; but in most cases, we’re only interested in whether the tests pass or fail, not the details of the failure (after the first one). This is particularly visible with flaky tests and causes significant delays in the release process.

We should add an option to abort on the first failure, and enable it when run from GHAs.

This would involve:

- [ ] Providing some way of controlling whether `make e2e` runs all tests or aborts on the first failure (at the Ginkgo level); this should default to run all tests, to preserve existing behaviour for local invocations.
- [ ] Setting up all the E2E GHAs to run `make e2e` with the setting to abort on first failure; this might involve changes in all projects.

This shouldn’t affect the GHA test matrices at all — we still want to run E2E in all desired configurations, the only change is that within each run, the first failure should abort _that_ run.

**Comment by dfarrell07** [comment]
> We should add an option to abort on the first failure, and enable it when run from GHAs.

This is how we can do that bit:

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

**Comment by mkolesnik** [comment]
```
jobs.<job_id>.strategy.fail-fast

When set to true, GitHub cancels all in-progress jobs if any matrix job fails. Default: true
```

There's a reason we set this to `false` though, since when we have only some combinations that fail it makes it much easier to know that only these combinations failed.

Additionally, you can always cancel a workflow manually, so I don't see a reason to lose this information.

**Comment by skitt** [comment]
This isn’t about controlling GHAs themselves; it’s about what happens inside `make e2e`. As Mike says we shouldn’t abort the matrix early. I’m only asking that `make e2e` itself abort on the first failure (so this is about Ginkgo configuration, not GHA configuration).

**Comment by mkolesnik** [comment]
Oh then that makes more sense IMO, perhaps you should update the description to make it clearer?

**Comment by dfarrell07** [comment]
We should be able to control this behavior with labels on PRs.

**Comment by dfarrell07** [comment]
Lighthouse E2E jobs that fail currently time out before finishing their post-mortem. This is being cited (see recent mentions of this issue above) as the correct solution, instead of increasing the E2E timeout. Wanted to clarify that as we consider the priority/implications here.

**Comment by astoycos** [comment]
Sorry I never got to this :(

**Comment by mkolesnik** [comment]
https://github.com/submariner-io/shipyard/pull/1082 will provide this base functionality, how crucial is it to have (yet another) label to control this?

**Comment by skitt** [comment]
> [submariner-io/shipyard#1082](https://github.com/submariner-io/shipyard/pull/1082) will provide this base functionality, how crucial is it to have (yet another) label to control this?

I don’t care about the label, the point is to be able to run all the tests if necessary. Whether that’s actually useful is debatable; perhaps we can start with 1082 and see if we miss the full test suites.

**Comment by mkolesnik** [comment]
+1 I think it's fine to start with fail-fast since you can re-run failed jobs individually anyhow, and should they pass youll get all tests anyway, and should they fail you can still examine post-mortem and figure out whats wrong.

I see no benefit to having multiple tests fail instead of one on the CI.

**Comment by skitt** [comment]
> +1 I think it's fine to start with fail-fast since you can re-run failed jobs individually anyhow, and should they pass youll get all tests anyway, and should they fail you can still examine post-mortem and figure out whats wrong.
> 
> I see no benefit to having multiple tests fail instead of one on the CI.

For users who have difficulty running e2e, it can be beneficial to get all the failures in one go; otherwise they could end up playing whack-a-mole.
