### ISSUE TITLE
Developer oriented scale testing

### ISSUE THREAD

**Issue by mkolesnik** [submariner-io/enhancements#49]
We would like to create tooling that allows running multiple kind clusters in scale testing on one or more machines, and run scale testing to identify any issues.

Tasks:
- [ ] [Develop ability to run scale tests: `make scale-test`](https://github.com/submariner-io/shipyard/issues/655)
- [ ] Document tooling on the website
- [ ] Run scale testing with the tool
- [ ] Run longevity testing with the tool

Stretch goals:

- [ ] Ability to generate load on the control plane

This tracker epic will also be updated with any issues identified during the scale & longevity testing

**Comment by nyechiel** [comment]
@mkolesnik can this be moved from 0.12?

**Comment by nyechiel** [comment]
@mkolesnik up to you, I think we can close and reopen when relevant.

**Comment by mkolesnik** [comment]
> @mkolesnik up to you, I think we can close and reopen when relevant.

Agreed, closing
