### ISSUE TITLE
subctl show command to return non-zero exit code on failed resource

### ISSUE THREAD

**Issue by manosnoam** [submariner-io/enhancements#5]
Does subctl show command returns non-zero exit code, if there's a missing/failed resource (e.g connections, networks, gateways, etc.) ?

If not, can you add this feature ?

**Comment by maayanf24** [comment]
@manosnoam  - In case no endpoints / connections / gateways , should the show cmd return non zero exit code as well?
Currently it will return non zero in some of the cases (no resource found)

**Comment by manosnoam** [comment]
@nyechiel @mangelajo @skitt 
What do you think ?

**Comment by nyechiel** [comment]
This was also discussed on Slack, and I like the approach suggested by @vthapar:

Non-zero exit code should only be used in case of failures. If there are no resources present, let's mimic kubectl's behavior and return a "no resource found" message.

**Comment by manosnoam** [comment]
Yep, "No resources found" returns exit code 0 in kubectl as well.
So please return non-zero just for errors in one of the resources.

**Comment by manosnoam** [comment]
Hi @maayanf24 , @nyechiel , @tpantelis ,
I see you closed this issue, but it's not yet verified...

Look at the Subctl error that happened in Submariner Cable-Driver, for example: https://github.com/submariner-io/submariner/issues/781

When I used `subctl show gateways` (or `show all`), the command did show there's an error in Subctl resources:
```
$ subctl show gateways

Showing information for cluster "nmanos-cluster-a":
NODE                HA STATUS       SUMMARY                         
ip-10-0-17-189      passive         There are no connections        
Showing information for cluster "nmanos-cluster-b":
NODE                HA STATUS       SUMMARY                         
default-cl1-ff6px-worker-kjg2nactive          0 connections out of 1 are established
```

However, the exit code was zero. Shouldn't it return non-zero rc here ?

**Comment by manosnoam** [comment]
@vthapar suggested that subctl should not return error code, since subctl got a result.
Unready state etc. is context specific to that resource, but not subctl show error.
Similarly to how kubectl doesn't throw error, if you do a get on pods, which are in an error state.
The command is subctl show and error should mean cli code failed to get sufficient information, not what the information actually is.

**Comment by tpantelis** [comment]
> Hi @maayanf24 , @nyechiel , @tpantelis ,
> I see you closed this issue, but it's not yet verified...
> 

This was to document an enhancement request. We verify implementation PRs  - I didn't think we said we'd verify enhancement requests.
