### ISSUE TITLE
Add support for Kube-OVN.

### ISSUE THREAD

**Issue by SoftTissues** [submariner-io/enhancements#62]
## Epic Description

Ovn-kubernetes is not so convenient to use. Please consider supporting Kube-OVN.

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

**Comment by dfarrell07** [comment]
This is related to https://github.com/submariner-io/submariner/issues/1598. Thanks @SoftTissues!

**Comment by dfarrell07** [comment]
This is also relevant: https://github.com/submariner-io/submariner/issues/778

**Comment by dfarrell07** [comment]
Discussing this on the PR/Issue scrub, we're not sure this make sense to add and support. We're already working on OVN-K8s support. If someone really wants this and will maintain it, we're open to discussion, closing for now.
