### ISSUE TITLE
Add support for finer-grained cluster connectivity options

### ISSUE THREAD

**Issue by nyechiel** [submariner-io/enhancements#68]
Submariner currently assumes full mesh by default, and provision VPN connections between all participating clusters. For some use cases, it makes sense to offer finer-grained connectivity options. This could also improve overall scalability/state maintained, for those cases in which full mesh is not required.

**Comment by mangelajo** [comment]
I remember @tpantelis also had some ideas about this. May be we shall do some brainstorming before writing an enhancement proposal would be good.

**Comment by aswinsuryan** [comment]
> is. May be we shall do some brainstorming before writing an enhancement proposal would be good.

Sure that will be great,  I will schedule a discussion.

**Comment by nyechiel** [comment]
We probably want to revisit https://github.com/submariner-io/enhancements/pull/4/files and not start from scratch

**Comment by tpantelis** [comment]
> We probably want to revisit https://github.com/submariner-io/enhancements/pull/4/files and not start from scratch

I updated that proposal to include fine-grained connectivity. We can discuss next week.

**Comment by tpantelis** [comment]
bump

**Comment by nyechiel** [comment]
EP: https://github.com/submariner-io/enhancements/pull/4

**Comment by tpantelis** [comment]
bump

**Comment by dfarrell07** [comment]
Related: https://github.com/submariner-io/enhancements/pull/4

**Comment by mkolesnik** [comment]
Supporting anything other than full mesh isnt a priority right now (over 2 years since this been opened).

I propose we close this and revisit if this becomes a priority.

**Comment by maayanf24** [comment]
This has been discussed on the issue scrub meeting and decided to close for now.
If this will become a priority it can be reopened
