### ISSUE TITLE
Rework kubeconfig/kubecontext handling in subctl

### ISSUE THREAD

**Issue by skitt** [submariner-io/enhancements#79]
The various `subctl` commands support a mixture of `KUBECONFIG` environment variables, `--kubeconfig` flags, `--kubecontext` flags, kubeconfig files etc.

We should make this consistent, ideally using `clientcmd`’s tools to handle kubeconfig. https://github.com/skitt/submariner-operator/pull/23 has an old attempt at this, using https://pkg.go.dev/k8s.io/client-go@v0.23.5/tools/clientcmd#BindOverrideFlags to provide access to all the features supported by `clientcmd` (see `kubectl options`).

For commands using a single context, _all_ the following should work, with kubeconfigs containing one or more clusters and/or contexts (this uses a `kube` prefix when setting up `clientcmd`):

```
# Use the default context in the kubeconfig
KUBECONFIG=/path/to/kubeconfig subctl foo
subctl foo --kubeconfig /path/to/kubeconfig
subctl --kubeconfig /path/to/kubeconfig foo

# Use the specified context from the kubeconfig
KUBECONFIG=/path/to/kubeconfig subctl foo --kubecontext bar
subctl foo --kubeconfig /path/to/kubeconfig --kubecontext bar
subctl --kubeconfig /path/to/kubeconfig --kubecontext bar foo
```

For commands using multiple contexts, the prefixes should make the purpose of each context clear, using appropriate prefixes when setting up `clientcmd`:

```
KUBECONFIG=/path/to/kubeconfig subctl benchmark latency --fromcontext foo --tocontext bar
subctl benchmark latency --kubeconfig /path/to/kubeconfig --fromcontext foo --tocontext bar
```

`--kubeconfig` is preserved as-is, since users can use a single file combining all their contexts. However such commands should also support separate kubeconfigs:

```
subctl benchmark latency --fromconfig /path/to/fromconfig --toconfig /path/to/toconfig
```

`clientcmd` _doesn’t_ handle `--kubeconfig` itself, that needs to be handled by `subctl`.

This enhancement should also include a test suite covering all the different possibilities. As far as possible, the 0.12 options should keep their existing behaviour, and be marked for deprecation; they will be removed after 0.13.

This would subsume submariner-io/subctl#49

**Comment by dfarrell07** [comment]
This seems to depend on two serial Epics, so it would seem not likely to get done in 0.13. The EP is also being reviewed. We also don't have Stephen for discussion, and he's also working on other big ones like the Operator SDK. Moving this from the 0.13 release for now.

**Comment by nyechiel** [comment]
@skitt I think this is actually in progress?

**Comment by skitt** [comment]
> @skitt I think this is actually in progress?

It is indeed, and part of it has been merged already (https://github.com/submariner-io/subctl/pull/242). There are a number of issues in GH and BZ which will be addressed by this once it’s done, I’ll be updating the issues as appropriate.

**Comment by skitt** [comment]
This is done for 0.14.
