### ISSUE TITLE
Epic: Hub controller for lighthouse

### ISSUE THREAD

**Issue by donaldh** [submariner-io/enhancements#83]
## Epic Description

The goal of this epic is to implement ServiceImport merging.

Once an mcs-controller has been introduced, the reconciliation logic will be extended to address
the following open issues:

- Mark conflicting `ServiceExport` objects with the `ServiceExportConflict` condition
- Merge matching `ServiceExport` objects into a single `ServiceImport` object

Related enhancement proposal: #111  

## Acceptance Criteria

Lighthouse behaviour aligns with MCS specification:

- Mark conflicting ServiceExport objects with the ServiceExportConflict condition
- Merge matching ServiceExport objects into a single ServiceImport object

## Definition of Done (Checklist)

* [ ] Code complete
* [ ] Relevant metrics added
* [ ] The acceptance criteria met
* [ ] Unit/e2e test added & pass
* [ ] CI jobs pass
* [ ] Deployed using cloud-prepare+subctl
* [ ] Deployed using ACM/OCM addon
* [ ] Deploy using Helm
* [ ] Deployed on supported platforms (for e.g kind, OCP on AWS, OCP on GCP)
* [ ] Run subctl verify, diagnose and gather
* [ ] Uninstall
* [ ] Troubleshooting (gather/diagnose) added
* [ ] Documentation added
* [ ] Release notes added

**Comment by donaldh** [comment]
[Aggregate ServiceImports](https://github.com/orgs/submariner-io/projects/15#card-65798653)
[Updating an exported service is not handled](https://github.com/orgs/submariner-io/projects/15#card-78014265)
[GlobalNet - exported service isn't reachable using desired port after service port edit](https://github.com/submariner-io/submariner/issues/1738)
[GlobalNet- exported service isn't reachable after service re creation](https://github.com/submariner-io/submariner/issues/1734)

**Comment by vthapar** [comment]
@donaldh Any specific reason why we need a hub controller and cant make this work without needing a centralized mcscontroller? Having a serverless broker has been one of the core design tenent of submariner. If we want to introduce a central controller to run on broker, it should be with a good enough reason. Note that an mcs controller with come withs own overhead of HA etc.

**Comment by donaldh** [comment]
@vthapar I have described the reason in enhancement pr #82

**Comment by dfarrell07** [comment]
It seems like https://github.com/submariner-io/enhancements/pull/82 is closed, and this Epic doesn't track https://github.com/submariner-io/enhancements/pull/111. Should it be updated?

**Comment by donaldh** [comment]
Good catch @dfarrell07, I have updated the title and description to match the ER.

**Comment by maayanf24** [comment]
Talked on the planning call - Not a priority for now
